#language: python
#python:
#  - "3.8"
# command to install dependencies
#install:

#  - pip install -e
# command to run tests
#script: python -m pytest
language: python

install:
- travis_retry pip install -e .
- pip install altair
- pip install ipywidgets 
- pip install pandas

script:
- coverage run -m unittest discover


after_success:
- coveralls
