#language: python
#python:
#  - "3.8"
# command to install dependencies
#install:

#  - pip install -e
# command to run tests
#script: python -m pytest
language: python

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
- pip install pytest
- pip install altair
- pip install ipywidgets 
- pip install pandas

script:
- python test_columns.py

after_success:
- coveralls
